// Code generated by ent, DO NOT EDIT.

package ent

import (
	"TinyCRM/ent/expert"
	"TinyCRM/ent/schema"
	"TinyCRM/ent/ticket"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	expertFields := schema.Expert{}.Fields()
	_ = expertFields
	// expertDescUsername is the schema descriptor for username field.
	expertDescUsername := expertFields[1].Descriptor()
	// expert.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	expert.UsernameValidator = expertDescUsername.Validators[0].(func(string) error)
	// expertDescFirstName is the schema descriptor for first_name field.
	expertDescFirstName := expertFields[2].Descriptor()
	// expert.FirstNameValidator is a validator for the "first_name" field. It is called by the builders before save.
	expert.FirstNameValidator = expertDescFirstName.Validators[0].(func(string) error)
	// expertDescLastName is the schema descriptor for last_name field.
	expertDescLastName := expertFields[3].Descriptor()
	// expert.LastNameValidator is a validator for the "last_name" field. It is called by the builders before save.
	expert.LastNameValidator = expertDescLastName.Validators[0].(func(string) error)
	// expertDescStartTime is the schema descriptor for start_time field.
	expertDescStartTime := expertFields[4].Descriptor()
	// expert.DefaultStartTime holds the default value on creation for the start_time field.
	expert.DefaultStartTime = expertDescStartTime.Default.(func() time.Time)
	// expertDescEndTime is the schema descriptor for end_time field.
	expertDescEndTime := expertFields[5].Descriptor()
	// expert.DefaultEndTime holds the default value on creation for the end_time field.
	expert.DefaultEndTime = expertDescEndTime.Default.(func() time.Time)
	ticketFields := schema.Ticket{}.Fields()
	_ = ticketFields
	// ticketDescTitle is the schema descriptor for title field.
	ticketDescTitle := ticketFields[1].Descriptor()
	// ticket.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	ticket.TitleValidator = ticketDescTitle.Validators[0].(func(string) error)
	// ticketDescContent is the schema descriptor for content field.
	ticketDescContent := ticketFields[2].Descriptor()
	// ticket.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	ticket.ContentValidator = ticketDescContent.Validators[0].(func(string) error)
}
