// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Customer is the predicate function for customer builders.
type Customer func(*sql.Selector)

// Department is the predicate function for department builders.
type Department func(*sql.Selector)

// Expert is the predicate function for expert builders.
type Expert func(*sql.Selector)

// Ticket is the predicate function for ticket builders.
type Ticket func(*sql.Selector)
